#!/usr/bin/env python3
"""
Visual demonstration of the sender_id None fix
Shows before/after behavior with the exact event from the logs
"""

def show_before():
    """Show the problematic behavior before the fix"""
    print("\n" + "="*70)
    print("BEFORE FIX - Crash with TypeError")
    print("="*70 + "\n")
    
    print("Event received:")
    print("  type: CONTACT_MSG_RECV")
    print("  payload: {")
    print("    'type': 'PRIV',")
    print("    'SNR': 12.5,")
    print("    'pubkey_prefix': '143bcd7f1b1f',  # ⚠️  Only this, no sender_id!")
    print("    'path_len': 255,")
    print("    'txt_type': 0,")
    print("    'sender_timestamp': 1768922280,")
    print("    'text': '/help'")
    print("  }")
    print()
    
    print("Code execution:")
    print("  sender_id = payload.get('contact_id') or payload.get('sender_id')")
    print("  # sender_id = None (not found in payload)")
    print()
    print("  info_print(f\"De: 0x{sender_id:08x} | Message: {text}\")")
    print("           " + " "*13 + "^" * 15)
    print("           " + " "*13 + "❌ CRASH HERE!")
    print()
    
    print("Error:")
    print("  ❌ TypeError: unsupported format string passed to NoneType.__format__")
    print("  📛 Bot stops processing the message")
    print("  📛 User receives no response")
    print()

def show_after():
    """Show the fixed behavior after the fix"""
    print("\n" + "="*70)
    print("AFTER FIX - Graceful Handling ✅")
    print("="*70 + "\n")
    
    print("Event received:")
    print("  type: CONTACT_MSG_RECV")
    print("  payload: {")
    print("    'type': 'PRIV',")
    print("    'SNR': 12.5,")
    print("    'pubkey_prefix': '143bcd7f1b1f',  # ✅ Will be used as fallback")
    print("    'path_len': 255,")
    print("    'txt_type': 0,")
    print("    'sender_timestamp': 1768922280,")
    print("    'text': '/help'")
    print("  }")
    print()
    
    print("Code execution:")
    print("  # Try multiple sources")
    print("  sender_id = None")
    print("  sender_id = payload.get('contact_id') or payload.get('sender_id')")
    print("  # sender_id = None")
    print()
    print("  if sender_id is None and hasattr(event, 'attributes'):")
    print("      sender_id = attributes.get('contact_id') or attributes.get('sender_id')")
    print("  # sender_id = None")
    print()
    print("  if sender_id is None and hasattr(event, 'contact_id'):")
    print("      sender_id = event.contact_id")
    print("  # sender_id = None")
    print()
    
    print("Safe formatting:")
    print("  if sender_id is not None:")
    print("      info_print(f\"De: 0x{sender_id:08x} | Message: {text}\")")
    print("  else:")
    print("      pubkey_prefix = payload.get('pubkey_prefix')")
    print("      if pubkey_prefix:")
    print("          info_print(f\"De: {pubkey_prefix} | Message: {text}\")")
    print("                         ^" * 14)
    print("                         ✅ Fallback to pubkey_prefix")
    print()
    
    print("Output:")
    print("  ✅ [INFO] 📬 [MESHCORE-DM] De: 143bcd7f1b1f | Message: /help")
    print("  ✅ Packet created with from: 0xFFFFFFFF (default)")
    print("  ✅ Bot processes the message successfully")
    print("  ✅ User receives a response")
    print()

def show_comparison():
    """Show side-by-side comparison"""
    print("\n" + "="*70)
    print("COMPARISON")
    print("="*70 + "\n")
    
    print("┌─────────────────────────────────┬─────────────────────────────────┐")
    print("│          BEFORE (Bad)           │          AFTER (Good)           │")
    print("├─────────────────────────────────┼─────────────────────────────────┤")
    print("│ sender_id = payload.get(...)    │ sender_id = None                │")
    print("│ # sender_id = None              │                                 │")
    print("│                                 │ # Try multiple sources          │")
    print("│                                 │ if isinstance(payload, dict):   │")
    print("│                                 │     sender_id = payload.get...  │")
    print("│                                 │                                 │")
    print("│                                 │ if sender_id is None:           │")
    print("│                                 │     sender_id = attributes.get..│")
    print("│                                 │                                 │")
    print("│                                 │ if sender_id is None:           │")
    print("│                                 │     sender_id = event.contact_id│")
    print("├─────────────────────────────────┼─────────────────────────────────┤")
    print("│ f\"0x{sender_id:08x}\"            │ if sender_id is not None:       │")
    print("│        ↓                        │     f\"0x{sender_id:08x}\"         │")
    print("│ ❌ TypeError!                    │ else:                           │")
    print("│ ❌ Crash!                        │     pubkey = payload.get(...)   │")
    print("│                                 │     if pubkey:                  │")
    print("│                                 │         f\"{pubkey}\"              │")
    print("│                                 │     ✅ No crash!                 │")
    print("├─────────────────────────────────┼─────────────────────────────────┤")
    print("│ 'from': sender_id               │ 'from': sender_id if ... else   │")
    print("│         ↓                       │         0xFFFFFFFF              │")
    print("│ 'from': None                    │ 'from': 0xFFFFFFFF              │")
    print("│ ❌ Invalid packet                │ ✅ Valid packet                  │")
    print("└─────────────────────────────────┴─────────────────────────────────┘")
    print()

def main():
    """Main demo"""
    print("\n" + "🔧"*35)
    print("VISUAL DEMONSTRATION: sender_id None Fix")
    print("🔧"*35)
    
    show_before()
    show_after()
    show_comparison()
    
    print("\n" + "="*70)
    print("SUMMARY")
    print("="*70 + "\n")
    print("The fix implements THREE key improvements:")
    print()
    print("1. 🔍 MULTI-SOURCE EXTRACTION")
    print("   Try payload → attributes → event object")
    print()
    print("2. ✅ SAFE FORMATTING")
    print("   Check if sender_id is None before using :08x format")
    print()
    print("3. 🔄 GRACEFUL FALLBACK")
    print("   Use pubkey_prefix when sender_id not available")
    print("   Use 0xFFFFFFFF as default packet value")
    print()
    print("Result: No more TypeError crashes! 🎉")
    print()

if __name__ == "__main__":
    main()
