
graph TD
    %% Styles
    classDef node fill:#f9f
    classDef rpi fill:#bbf
    

    %% Nodes
    RPi5["Raspberry Pi 5 (Host)"]:::rpi
    Meshtastic-bot["Meshtastic Node 1 (Port Série)"]:::node
    Meshtastic-router["Meshtastic Node 2 (TCP/IP)"]:::node

    %% Connections
    RPi5 -- "/dev/ttyXXX (UART/USB)" --> Meshtastic-bot:::connection
    RPi5 -- "192.168.1.38:PORT (WiFi/Ethernet)" --> Meshtastic-router:::connection
   
